### ISSUE TITLE
Small errors in page

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/ai4gov-website#4]
- In "team" there is a member called "XXXXXXX". 
- In team, Claudio Feijoo's pic has a different size from the rest of the team.
- In "team" I would add the organizations in the picture description, rather than have to guess who is from where.
- Replace "Call" by "Phone"
- The footer has all 4 organizations on the right, which leaves a very awkward space in the rest of the page

**Comment by ocorcho** [comment]
Fixed
