### ISSUE TITLE
"Promoted by" logo size

### ISSUE THREAD

**Issue by daniel-dona** [oeg-upm/ai4gov-website#5]
Could be a small visual enhancement  to reduce the "Promoted by" logos

![imagen](https://user-images.githubusercontent.com/23705091/123396918-26f5e700-d5a2-11eb-808b-77ad02e2274d.png)

![imagen](https://user-images.githubusercontent.com/23705091/123396852-15acda80-d5a2-11eb-8401-e635b834c859.png)

**Comment by ocorcho** [comment]
Fixed
